# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exportWidget.ui',
# licensing of 'exportWidget.ui' applies.
#
# Created: Thu Oct 25 16:52:46 2018
#      by: pyside2-uic  running on PySide2 5.11.0a1.dev1528378291
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_mainWidget(object):
    def setupUi(self, mainWidget):
        mainWidget.setObjectName("mainWidget")
        mainWidget.resize(553, 809)
        self.mainLayout = QtWidgets.QVBoxLayout(mainWidget)
        self.mainLayout.setSpacing(10)
        self.mainLayout.setContentsMargins(10, 10, 10, 10)
        self.mainLayout.setObjectName("mainLayout")
        self.scrollArea = QtWidgets.QScrollArea(mainWidget)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollWidget = QtWidgets.QWidget()
        self.scrollWidget.setGeometry(QtCore.QRect(0, 0, 533, 754))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollWidget.sizePolicy().hasHeightForWidth())
        self.scrollWidget.setSizePolicy(sizePolicy)
        self.scrollWidget.setObjectName("scrollWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.headerLabel = QtWidgets.QLabel(self.scrollWidget)
        self.headerLabel.setMinimumSize(QtCore.QSize(0, 25))
        self.headerLabel.setMaximumSize(QtCore.QSize(16777215, 25))
        self.headerLabel.setText("Animation")
        self.headerLabel.setTextFormat(QtCore.Qt.AutoText)
        self.headerLabel.setObjectName("headerLabel")
        self.verticalLayout_2.addWidget(self.headerLabel)
        self.thumbailBox = QtWidgets.QGroupBox(self.scrollWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thumbailBox.sizePolicy().hasHeightForWidth())
        self.thumbailBox.setSizePolicy(sizePolicy)
        self.thumbailBox.setTitle("Thumbnail")
        self.thumbailBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.thumbailBox.setFlat(False)
        self.thumbailBox.setCheckable(False)
        self.thumbailBox.setChecked(False)
        self.thumbailBox.setObjectName("thumbailBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.thumbailBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.thumbnailImage = QtWidgets.QLabel(self.thumbailBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thumbnailImage.sizePolicy().hasHeightForWidth())
        self.thumbnailImage.setSizePolicy(sizePolicy)
        self.thumbnailImage.setMinimumSize(QtCore.QSize(200, 200))
        self.thumbnailImage.setMaximumSize(QtCore.QSize(200, 16777215))
        self.thumbnailImage.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.thumbnailImage.setFrameShape(QtWidgets.QFrame.Box)
        self.thumbnailImage.setText("")
        self.thumbnailImage.setPixmap(QtGui.QPixmap("icons/image_icon_128.png"))
        self.thumbnailImage.setAlignment(QtCore.Qt.AlignCenter)
        self.thumbnailImage.setObjectName("thumbnailImage")
        self.horizontalLayout.addWidget(self.thumbnailImage)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.rangeLayout = QtWidgets.QHBoxLayout()
        self.rangeLayout.setObjectName("rangeLayout")
        self.rangeLabel = QtWidgets.QLabel(self.thumbailBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rangeLabel.sizePolicy().hasHeightForWidth())
        self.rangeLabel.setSizePolicy(sizePolicy)
        self.rangeLabel.setMinimumSize(QtCore.QSize(60, 25))
        self.rangeLabel.setMaximumSize(QtCore.QSize(60, 16777215))
        self.rangeLabel.setText(" Range: ")
        self.rangeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rangeLabel.setObjectName("rangeLabel")
        self.rangeLayout.addWidget(self.rangeLabel)
        self.rangeStartWidget = QtWidgets.QSpinBox(self.thumbailBox)
        self.rangeStartWidget.setMaximumSize(QtCore.QSize(16777215, 25))
        self.rangeStartWidget.setFrame(False)
        self.rangeStartWidget.setObjectName("rangeStartWidget")
        self.rangeLayout.addWidget(self.rangeStartWidget)
        self.rangeEndWidget = QtWidgets.QSpinBox(self.thumbailBox)
        self.rangeEndWidget.setMaximumSize(QtCore.QSize(16777215, 25))
        self.rangeEndWidget.setFrame(False)
        self.rangeEndWidget.setProperty("value", 1)
        self.rangeEndWidget.setObjectName("rangeEndWidget")
        self.rangeLayout.addWidget(self.rangeEndWidget)
        self.rangeOptionsButton = QtWidgets.QPushButton(self.thumbailBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rangeOptionsButton.sizePolicy().hasHeightForWidth())
        self.rangeOptionsButton.setSizePolicy(sizePolicy)
        self.rangeOptionsButton.setMinimumSize(QtCore.QSize(25, 0))
        self.rangeOptionsButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.rangeOptionsButton.setText("...")
        self.rangeOptionsButton.setObjectName("rangeOptionsButton")
        self.rangeLayout.addWidget(self.rangeOptionsButton)
        self.verticalLayout_3.addLayout(self.rangeLayout)
        self.frameLayout = QtWidgets.QHBoxLayout()
        self.frameLayout.setObjectName("frameLayout")
        self.frameLabel = QtWidgets.QLabel(self.thumbailBox)
        self.frameLabel.setMinimumSize(QtCore.QSize(60, 25))
        self.frameLabel.setMaximumSize(QtCore.QSize(60, 16777215))
        self.frameLabel.setText("By Frame: ")
        self.frameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.frameLabel.setObjectName("frameLabel")
        self.frameLayout.addWidget(self.frameLabel)
        self.frameWidget = QtWidgets.QSpinBox(self.thumbailBox)
        self.frameWidget.setMaximumSize(QtCore.QSize(16777215, 25))
        self.frameWidget.setFrame(False)
        self.frameWidget.setKeyboardTracking(True)
        self.frameWidget.setSuffix("")
        self.frameWidget.setPrefix("")
        self.frameWidget.setProperty("value", 1)
        self.frameWidget.setObjectName("frameWidget")
        self.frameLayout.addWidget(self.frameWidget)
        self.verticalLayout_3.addLayout(self.frameLayout)
        self.verticalLayout_2.addWidget(self.thumbailBox)
        self.settingsBox = QtWidgets.QGroupBox(self.scrollWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingsBox.sizePolicy().hasHeightForWidth())
        self.settingsBox.setSizePolicy(sizePolicy)
        self.settingsBox.setTitle("Settings")
        self.settingsBox.setFlat(False)
        self.settingsBox.setCheckable(False)
        self.settingsBox.setObjectName("settingsBox")
        self.settingsBoxLayout = QtWidgets.QVBoxLayout(self.settingsBox)
        self.settingsBoxLayout.setSpacing(5)
        self.settingsBoxLayout.setContentsMargins(10, 10, 10, 10)
        self.settingsBoxLayout.setObjectName("settingsBoxLayout")
        self.nameLayout = QtWidgets.QHBoxLayout()
        self.nameLayout.setObjectName("nameLayout")
        self.nameLabel = QtWidgets.QLabel(self.settingsBox)
        self.nameLabel.setMinimumSize(QtCore.QSize(60, 25))
        self.nameLabel.setMaximumSize(QtCore.QSize(60, 16777215))
        self.nameLabel.setText("File Name: ")
        self.nameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nameLabel.setObjectName("nameLabel")
        self.nameLayout.addWidget(self.nameLabel)
        self.nameWidget = QtWidgets.QLineEdit(self.settingsBox)
        self.nameWidget.setMinimumSize(QtCore.QSize(0, 25))
        self.nameWidget.setMaximumSize(QtCore.QSize(16777215, 25))
        self.nameWidget.setObjectName("nameWidget")
        self.nameLayout.addWidget(self.nameWidget)
        self.settingsBoxLayout.addLayout(self.nameLayout)
        self.settingsExtraLayout = QtWidgets.QHBoxLayout()
        self.settingsExtraLayout.setObjectName("settingsExtraLayout")
        self.layersLayout = QtWidgets.QHBoxLayout()
        self.layersLayout.setObjectName("layersLayout")
        self.shapesLayout = QtWidgets.QHBoxLayout()
        self.shapesLayout.setObjectName("shapesLayout")
        self.shapesLabel = QtWidgets.QLabel(self.settingsBox)
        self.shapesLabel.setMinimumSize(QtCore.QSize(60, 25))
        self.shapesLabel.setMaximumSize(QtCore.QSize(60, 25))
        self.shapesLabel.setText("Shapes: ")
        self.shapesLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.shapesLabel.setObjectName("shapesLabel")
        self.shapesLayout.addWidget(self.shapesLabel)
        self.shapesCheckBox = QtWidgets.QCheckBox(self.settingsBox)
        self.shapesCheckBox.setText("")
        self.shapesCheckBox.setTristate(False)
        self.shapesCheckBox.setObjectName("shapesCheckBox")
        self.shapesLayout.addWidget(self.shapesCheckBox)
        self.layersLayout.addLayout(self.shapesLayout)
        self.layersLabel = QtWidgets.QLabel(self.settingsBox)
        self.layersLabel.setMinimumSize(QtCore.QSize(60, 25))
        self.layersLabel.setMaximumSize(QtCore.QSize(60, 16777215))
        self.layersLabel.setText("Layers: ")
        self.layersLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.layersLabel.setObjectName("layersLabel")
        self.layersLayout.addWidget(self.layersLabel)
        self.layersCheckBox = QtWidgets.QCheckBox(self.settingsBox)
        self.layersCheckBox.setText("")
        self.layersCheckBox.setTristate(False)
        self.layersCheckBox.setObjectName("layersCheckBox")
        self.layersLayout.addWidget(self.layersCheckBox)
        self.settingsExtraLayout.addLayout(self.layersLayout)
        self.settingsBoxLayout.addLayout(self.settingsExtraLayout)
        self.objectLayout = QtWidgets.QHBoxLayout()
        self.objectLayout.setObjectName("objectLayout")
        self.objectLabel = QtWidgets.QLabel(self.settingsBox)
        self.objectLabel.setMinimumSize(QtCore.QSize(60, 25))
        self.objectLabel.setMaximumSize(QtCore.QSize(60, 25))
        self.objectLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.objectLabel.setText("Objects: ")
        self.objectLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.objectLabel.setObjectName("objectLabel")
        self.objectLayout.addWidget(self.objectLabel)
        self.objectWidget = QtWidgets.QLabel(self.settingsBox)
        self.objectWidget.setMinimumSize(QtCore.QSize(0, 25))
        self.objectWidget.setMaximumSize(QtCore.QSize(16777215, 25))
        self.objectWidget.setText("0")
        self.objectWidget.setObjectName("objectWidget")
        self.objectLayout.addWidget(self.objectWidget)
        self.settingsBoxLayout.addLayout(self.objectLayout)
        self.verticalLayout_2.addWidget(self.settingsBox)
        self.commentBox = QtWidgets.QGroupBox(self.scrollWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commentBox.sizePolicy().hasHeightForWidth())
        self.commentBox.setSizePolicy(sizePolicy)
        self.commentBox.setMinimumSize(QtCore.QSize(0, 0))
        self.commentBox.setMaximumSize(QtCore.QSize(16777215, 100))
        self.commentBox.setTitle("Comment")
        self.commentBox.setFlat(False)
        self.commentBox.setObjectName("commentBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.commentBox)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.commentWidget = QtWidgets.QTextEdit(self.commentBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commentWidget.sizePolicy().hasHeightForWidth())
        self.commentWidget.setSizePolicy(sizePolicy)
        self.commentWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.commentWidget.setUndoRedoEnabled(True)
        self.commentWidget.setOverwriteMode(False)
        self.commentWidget.setObjectName("commentWidget")
        self.verticalLayout.addWidget(self.commentWidget)
        self.verticalLayout_2.addWidget(self.commentBox)
        self.tagsBox = QtWidgets.QGroupBox(self.scrollWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tagsBox.sizePolicy().hasHeightForWidth())
        self.tagsBox.setSizePolicy(sizePolicy)
        self.tagsBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tagsBox.setTitle("Tags")
        self.tagsBox.setFlat(False)
        self.tagsBox.setObjectName("tagsBox")
        self.tagsLayout = QtWidgets.QHBoxLayout(self.tagsBox)
        self.tagsLayout.setSpacing(5)
        self.tagsLayout.setContentsMargins(10, 10, 10, 10)
        self.tagsLayout.setObjectName("tagsLayout")
        self.tagsWidget = QtWidgets.QLineEdit(self.tagsBox)
        self.tagsWidget.setMinimumSize(QtCore.QSize(0, 25))
        self.tagsWidget.setMaximumSize(QtCore.QSize(16777215, 25))
        self.tagsWidget.setObjectName("tagsWidget")
        self.tagsLayout.addWidget(self.tagsWidget)
        self.verticalLayout_2.addWidget(self.tagsBox)
        self.scrollArea.setWidget(self.scrollWidget)
        self.mainLayout.addWidget(self.scrollArea)
        self.exportButton = QtWidgets.QPushButton(mainWidget)
        self.exportButton.setMinimumSize(QtCore.QSize(0, 25))
        self.exportButton.setMaximumSize(QtCore.QSize(16777215, 25))
        self.exportButton.setText("Export")
        self.exportButton.setObjectName("exportButton")
        self.mainLayout.addWidget(self.exportButton)

        self.retranslateUi(mainWidget)
        QtCore.QMetaObject.connectSlotsByName(mainWidget)

    def retranslateUi(self, mainWidget):
        mainWidget.setWindowTitle(QtWidgets.QApplication.translate("mainWidget", "Form", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWidget = QtWidgets.QWidget()
    ui = Ui_mainWidget()
    ui.setupUi(mainWidget)
    mainWidget.show()
    sys.exit(app.exec_())

