# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'infoWidget.ui',
# licensing of 'infoWidget.ui' applies.
#
# Created: Sat Oct 27 19:14:47 2018
#      by: pyside2-uic  running on PySide2 5.11.0a1.dev1528378291
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
	def setupUi(self, Form):
		Form.setObjectName("Form")
		Form.resize(386, 446)
		self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
		self.verticalLayout_2.setObjectName("verticalLayout_2")
		self.groupBox = QtWidgets.QGroupBox(Form)
		self.groupBox.setTitle("File Info.")
		self.groupBox.setObjectName("groupBox")

		self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
		self.verticalLayout.setObjectName("verticalLayout")
		self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_8.setObjectName("horizontalLayout_8")


		self.label_15 = QtWidgets.QLabel(self.groupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
		self.label_15.setSizePolicy(sizePolicy)
		self.label_15.setMinimumSize(QtCore.QSize(80, 20))
		self.label_15.setMaximumSize(QtCore.QSize(80, 20))
		self.label_15.setText("TextLabel")
		self.label_15.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
		self.label_15.setObjectName("label_15")
		self.horizontalLayout_8.addWidget(self.label_15)
		self.label_16 = QtWidgets.QLabel(self.groupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
		self.label_16.setSizePolicy(sizePolicy)
		self.label_16.setMinimumSize(QtCore.QSize(0, 20))
		self.label_16.setMaximumSize(QtCore.QSize(16777215, 20))
		self.label_16.setObjectName("label_16")
		self.horizontalLayout_8.addWidget(self.label_16)
		self.verticalLayout.addLayout(self.horizontalLayout_8)
		self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_7.setObjectName("horizontalLayout_7")
		self.label_13 = QtWidgets.QLabel(self.groupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
		self.label_13.setSizePolicy(sizePolicy)
		self.label_13.setMinimumSize(QtCore.QSize(80, 20))
		self.label_13.setMaximumSize(QtCore.QSize(80, 20))
		self.label_13.setText("TextLabel")
		self.label_13.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
		self.label_13.setObjectName("label_13")
		self.horizontalLayout_7.addWidget(self.label_13)
		self.label_14 = QtWidgets.QLabel(self.groupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
		self.label_14.setSizePolicy(sizePolicy)
		self.label_14.setMinimumSize(QtCore.QSize(0, 20))
		self.label_14.setMaximumSize(QtCore.QSize(16777215, 20))
		self.label_14.setObjectName("label_14")
		self.horizontalLayout_7.addWidget(self.label_14)
		self.verticalLayout.addLayout(self.horizontalLayout_7)
		self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_6.setObjectName("horizontalLayout_6")
		self.label_11 = QtWidgets.QLabel(self.groupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
		self.label_11.setSizePolicy(sizePolicy)
		self.label_11.setMinimumSize(QtCore.QSize(80, 20))
		self.label_11.setMaximumSize(QtCore.QSize(80, 20))
		self.label_11.setText("TextLabel")
		self.label_11.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
		self.label_11.setObjectName("label_11")
		self.horizontalLayout_6.addWidget(self.label_11)
		self.label_12 = QtWidgets.QLabel(self.groupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
		self.label_12.setSizePolicy(sizePolicy)
		self.label_12.setMinimumSize(QtCore.QSize(0, 20))
		self.label_12.setMaximumSize(QtCore.QSize(16777215, 20))
		self.label_12.setObjectName("label_12")
		self.horizontalLayout_6.addWidget(self.label_12)
		self.verticalLayout.addLayout(self.horizontalLayout_6)
		self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_5.setObjectName("horizontalLayout_5")
		self.label_9 = QtWidgets.QLabel(self.groupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
		self.label_9.setSizePolicy(sizePolicy)
		self.label_9.setMinimumSize(QtCore.QSize(80, 20))
		self.label_9.setMaximumSize(QtCore.QSize(80, 20))
		self.label_9.setText("TextLabel")
		self.label_9.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
		self.label_9.setObjectName("label_9")
		self.horizontalLayout_5.addWidget(self.label_9)
		self.label_10 = QtWidgets.QLabel(self.groupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
		self.label_10.setSizePolicy(sizePolicy)
		self.label_10.setMinimumSize(QtCore.QSize(0, 20))
		self.label_10.setMaximumSize(QtCore.QSize(16777215, 20))
		self.label_10.setObjectName("label_10")
		self.horizontalLayout_5.addWidget(self.label_10)
		self.verticalLayout.addLayout(self.horizontalLayout_5)
		self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_4.setObjectName("horizontalLayout_4")
		self.label_7 = QtWidgets.QLabel(self.groupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
		self.label_7.setSizePolicy(sizePolicy)
		self.label_7.setMinimumSize(QtCore.QSize(80, 20))
		self.label_7.setMaximumSize(QtCore.QSize(80, 20))
		self.label_7.setText("TextLabel")
		self.label_7.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
		self.label_7.setObjectName("label_7")
		self.horizontalLayout_4.addWidget(self.label_7)
		self.label_8 = QtWidgets.QLabel(self.groupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
		self.label_8.setSizePolicy(sizePolicy)
		self.label_8.setMinimumSize(QtCore.QSize(0, 20))
		self.label_8.setMaximumSize(QtCore.QSize(16777215, 20))
		self.label_8.setObjectName("label_8")
		self.horizontalLayout_4.addWidget(self.label_8)
		self.verticalLayout.addLayout(self.horizontalLayout_4)
		self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_3.setObjectName("horizontalLayout_3")
		self.label_6 = QtWidgets.QLabel(self.groupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
		self.label_6.setSizePolicy(sizePolicy)
		self.label_6.setMinimumSize(QtCore.QSize(80, 20))
		self.label_6.setMaximumSize(QtCore.QSize(80, 20))
		self.label_6.setText("TextLabel")
		self.label_6.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
		self.label_6.setObjectName("label_6")
		self.horizontalLayout_3.addWidget(self.label_6)
		self.label_3 = QtWidgets.QLabel(self.groupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
		self.label_3.setSizePolicy(sizePolicy)
		self.label_3.setMinimumSize(QtCore.QSize(0, 20))
		self.label_3.setMaximumSize(QtCore.QSize(16777215, 20))
		self.label_3.setObjectName("label_3")
		self.horizontalLayout_3.addWidget(self.label_3)
		self.verticalLayout.addLayout(self.horizontalLayout_3)
		self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_2.setObjectName("horizontalLayout_2")
		self.label_5 = QtWidgets.QLabel(self.groupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
		self.label_5.setSizePolicy(sizePolicy)
		self.label_5.setMinimumSize(QtCore.QSize(80, 20))
		self.label_5.setMaximumSize(QtCore.QSize(80, 20))
		self.label_5.setText("TextLabel")
		self.label_5.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
		self.label_5.setObjectName("label_5")
		self.horizontalLayout_2.addWidget(self.label_5)
		self.label_2 = QtWidgets.QLabel(self.groupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
		self.label_2.setSizePolicy(sizePolicy)
		self.label_2.setMinimumSize(QtCore.QSize(0, 20))
		self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
		self.label_2.setObjectName("label_2")
		self.horizontalLayout_2.addWidget(self.label_2)
		self.verticalLayout.addLayout(self.horizontalLayout_2)
		self.horizontalLayout = QtWidgets.QHBoxLayout()
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.label_4 = QtWidgets.QLabel(self.groupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
		self.label_4.setSizePolicy(sizePolicy)
		self.label_4.setMinimumSize(QtCore.QSize(80, 20))
		self.label_4.setMaximumSize(QtCore.QSize(80, 20))
		self.label_4.setText("TextLabel")
		self.label_4.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
		self.label_4.setObjectName("label_4")
		self.horizontalLayout.addWidget(self.label_4)
		self.label = QtWidgets.QLabel(self.groupBox)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
		self.label.setSizePolicy(sizePolicy)
		self.label.setMinimumSize(QtCore.QSize(0, 20))
		self.label.setMaximumSize(QtCore.QSize(16777215, 20))
		self.label.setObjectName("label")
		self.horizontalLayout.addWidget(self.label)
		self.verticalLayout.addLayout(self.horizontalLayout)
		spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
		self.verticalLayout.addItem(spacerItem)
		self.verticalLayout_2.addWidget(self.groupBox)

		self.retranslateUi(Form)
		QtCore.QMetaObject.connectSlotsByName(Form)

	def retranslateUi(self, Form):
		Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
		self.label_16.setText(QtWidgets.QApplication.translate("Form", "TextLabel", None, -1))
		self.label_14.setText(QtWidgets.QApplication.translate("Form", "TextLabel", None, -1))
		self.label_12.setText(QtWidgets.QApplication.translate("Form", "TextLabel", None, -1))
		self.label_10.setText(QtWidgets.QApplication.translate("Form", "TextLabel", None, -1))
		self.label_8.setText(QtWidgets.QApplication.translate("Form", "TextLabel", None, -1))
		self.label_3.setText(QtWidgets.QApplication.translate("Form", "TextLabel", None, -1))
		self.label_2.setText(QtWidgets.QApplication.translate("Form", "TextLabel", None, -1))
		self.label.setText(QtWidgets.QApplication.translate("Form", "TextLabel", None, -1))


if __name__ == "__main__":
	import sys

	app = QtWidgets.QApplication(sys.argv)
	Form = QtWidgets.QWidget()
	ui = Ui_Form()
	ui.setupUi(Form)
	Form.show()
	sys.exit(app.exec_())
