# Qt Modules
from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		
		self.widget_main = QWidget(MainWindow)
		self.widget_main.setObjectName("widget_main")
		self.layout_main = QVBoxLayout(self.widget_main)
		self.layout_main.setSpacing(3)
		self.layout_main.setContentsMargins(3, 3, 3, 3)
		self.layout_main.setObjectName("layout_main")
		self.widget_header = QWidget(self.widget_main)
		sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.widget_header.sizePolicy().hasHeightForWidth())
		self.widget_header.setSizePolicy(sizePolicy)
		self.widget_header.setMinimumSize(QSize(0, 56))
		self.widget_header.setMaximumSize(QSize(16777215, 16777215))
		self.widget_header.setStyleSheet("background:black;")
		self.widget_header.setObjectName("widget_header")
		self.layout_header = QHBoxLayout(self.widget_header)
		self.layout_header.setSpacing(10)
		self.layout_header.setContentsMargins(10, 10, 10, 10)
		self.layout_header.setObjectName("layout_header")
		self.label_logo = QLabel(self.widget_header)
		self.label_logo.setMinimumSize(QSize(114, 14))
		self.label_logo.setText("")
		self.label_logo.setPixmap(QPixmap(":/icon/icon_logo.png"))
		self.label_logo.setObjectName("label_logo")
		self.layout_header.addWidget(self.label_logo)
		self.button_settings = QToolButton(self.widget_header)
		self.button_settings.setMinimumSize(QSize(34, 34))
		self.button_settings.setMaximumSize(QSize(34, 34))
		icon = QIcon()
		icon.addPixmap(QPixmap(":/icon/icon_gear.png"), QIcon.Normal, QIcon.Off)
		self.button_settings.setIcon(icon)
		self.button_settings.setIconSize(QSize(32, 32))
		self.button_settings.setAutoRaise(False)
		self.button_settings.setObjectName("button_settings")
		self.layout_header.addWidget(self.button_settings)
		self.layout_main.addWidget(self.widget_header)
		self.widget_pane = QSplitter(self.widget_main)
		self.widget_pane.setLayoutDirection(Qt.LeftToRight)
		self.widget_pane.setFrameShape(QFrame.NoFrame)
		self.widget_pane.setFrameShadow(QFrame.Plain)
		self.widget_pane.setOrientation(Qt.Vertical)
		self.widget_pane.setHandleWidth(8)
		self.widget_pane.setObjectName("widget_pane")
		self.widget_channelbox = QWidget(self.widget_pane)
		self.widget_channelbox.setObjectName("widget_channelbox")
		self.layout_channelbox = QVBoxLayout(self.widget_channelbox)
		self.layout_channelbox.setSpacing(0)
		self.layout_channelbox.setContentsMargins(0, 0, 0, 0)
		self.layout_channelbox.setObjectName("layout_channelbox")
		self.widget_tab_channelbox = QTabWidget(self.widget_channelbox)
		self.widget_tab_channelbox.setObjectName("widget_tab_channelbox")
		self.tab_channelbox = QWidget()
		self.tab_channelbox.setObjectName("tab_channelbox")
		self.layout_tab_channelbox = QVBoxLayout(self.tab_channelbox)
		self.layout_tab_channelbox.setSpacing(3)
		self.layout_tab_channelbox.setContentsMargins(3, 3, 3, 3)
		self.layout_tab_channelbox.setObjectName("layout_tab_channelbox")
		self.lineEdit = QLineEdit(self.tab_channelbox)
		self.lineEdit.setObjectName("lineEdit")
		self.layout_tab_channelbox.addWidget(self.lineEdit)
		self.treeWidget = QTreeWidget(self.tab_channelbox)
		self.treeWidget.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
		self.treeWidget.setUniformRowHeights(True)
		self.treeWidget.setItemsExpandable(True)
		self.treeWidget.setHeaderHidden(True)
		self.treeWidget.setObjectName("treeWidget")
		item_0 = QTreeWidgetItem(self.treeWidget)
		item_0 = QTreeWidgetItem(self.treeWidget)
		item_0 = QTreeWidgetItem(self.treeWidget)
		item_0 = QTreeWidgetItem(self.treeWidget)
		item_0 = QTreeWidgetItem(self.treeWidget)
		item_0 = QTreeWidgetItem(self.treeWidget)
		item_0 = QTreeWidgetItem(self.treeWidget)
		item_0 = QTreeWidgetItem(self.treeWidget)
		item_0 = QTreeWidgetItem(self.treeWidget)
		item_0 = QTreeWidgetItem(self.treeWidget)
		self.treeWidget.header().setVisible(False)
		self.treeWidget.header().setDefaultSectionSize(100)
		self.layout_tab_channelbox.addWidget(self.treeWidget)
		self.widget_tab_channelbox.addTab(self.tab_channelbox, "")
		self.layout_channelbox.addWidget(self.widget_tab_channelbox)
		self.widget_layers = QWidget(self.widget_pane)
		self.widget_layers.setObjectName("widget_layers")
		self.layout_layers = QVBoxLayout(self.widget_layers)
		self.layout_layers.setSpacing(0)
		self.layout_layers.setContentsMargins(0, 0, 0, 0)
		self.layout_layers.setObjectName("layout_layers")
		self.widget_tab_layers = QTabWidget(self.widget_layers)
		self.widget_tab_layers.setObjectName("widget_tab_layers")
		self.tab_layers = QWidget()
		self.tab_layers.setObjectName("tab_layers")
		self.layout_tab_layers = QVBoxLayout(self.tab_layers)
		self.layout_tab_layers.setSpacing(3)
		self.layout_tab_layers.setContentsMargins(3, 3, 3, 3)
		self.layout_tab_layers.setObjectName("layout_tab_layers")
		self.treeWidget_2 = QTreeWidget(self.tab_layers)
		self.treeWidget_2.setStyleSheet("background:#282f37;")
		self.treeWidget_2.setHeaderHidden(True)
		self.treeWidget_2.setObjectName("treeWidget_2")
		self.treeWidget_2.headerItem().setText(0, "1")
		self.layout_tab_layers.addWidget(self.treeWidget_2)
		self.widget_layers_tools = QWidget(self.tab_layers)
		sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.widget_layers_tools.sizePolicy().hasHeightForWidth())
		self.widget_layers_tools.setSizePolicy(sizePolicy)
		self.widget_layers_tools.setLayoutDirection(Qt.RightToLeft)
		self.widget_layers_tools.setObjectName("widget_layers_tools")
		self.layout_layers_tools = QHBoxLayout(self.widget_layers_tools)
		self.layout_layers_tools.setSpacing(3)
		self.layout_layers_tools.setContentsMargins(3, 3, 3, 3)
		self.layout_layers_tools.setObjectName("layout_layers_tools")
		self.toolButton_3 = QToolButton(self.widget_layers_tools)
		self.toolButton_3.setObjectName("toolButton_3")
		self.layout_layers_tools.addWidget(self.toolButton_3)
		self.toolButton_2 = QToolButton(self.widget_layers_tools)
		self.toolButton_2.setObjectName("toolButton_2")
		self.layout_layers_tools.addWidget(self.toolButton_2)
		self.toolButton_4 = QToolButton(self.widget_layers_tools)
		self.toolButton_4.setObjectName("toolButton_4")
		self.layout_layers_tools.addWidget(self.toolButton_4)
		self.layout_tab_layers.addWidget(self.widget_layers_tools)
		self.widget_tab_layers.addTab(self.tab_layers, "")
		self.tab_anim = QWidget()
		self.tab_anim.setObjectName("tab_anim")
		self.widget_tab_layers.addTab(self.tab_anim, "")
		self.layout_layers.addWidget(self.widget_tab_layers)
		self.widget_custom = QWidget(self.widget_pane)
		self.widget_custom.setObjectName("widget_custom")
		self.layout_custom = QVBoxLayout(self.widget_custom)
		self.layout_custom.setSpacing(0)
		self.layout_custom.setContentsMargins(0, 0, 0, 0)
		self.layout_custom.setObjectName("layout_custom")
		self.widget_tab_custom = QTabWidget(self.widget_custom)
		self.widget_tab_custom.setObjectName("widget_tab_custom")
		self.tab_tools = QWidget()
		self.tab_tools.setObjectName("tab_tools")
		self.verticalLayout_7 = QVBoxLayout(self.tab_tools)
		self.verticalLayout_7.setSpacing(3)
		self.verticalLayout_7.setContentsMargins(3, 3, 3, 3)
		self.verticalLayout_7.setObjectName("verticalLayout_7")
		self.scrollArea = QScrollArea(self.tab_tools)
		self.scrollArea.setWidgetResizable(True)
		self.scrollArea.setObjectName("scrollArea")
		self.scrollAreaWidgetContents = QWidget()
		self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 471, 75))
		self.scrollAreaWidgetContents.setAutoFillBackground(True)
		self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
		self.verticalLayout = QVBoxLayout(self.scrollAreaWidgetContents)
		self.verticalLayout.setObjectName("verticalLayout")
		self.pushButton = QPushButton(self.scrollAreaWidgetContents)
		self.pushButton.setObjectName("pushButton")
		self.verticalLayout.addWidget(self.pushButton)
		self.scrollArea.setWidget(self.scrollAreaWidgetContents)
		self.verticalLayout_7.addWidget(self.scrollArea)
		self.widget_tab_custom.addTab(self.tab_tools, "")
		self.layout_custom.addWidget(self.widget_tab_custom)
		self.layout_main.addWidget(self.widget_pane)
		MainWindow.setCentralWidget(self.widget_main)
		self.menubar = QMenuBar(MainWindow)
		self.menubar.setGeometry(QRect(0, 0, 485, 18))
		self.menubar.setObjectName("menubar")
		MainWindow.setMenuBar(self.menubar)
		
		self.retranslateUi(MainWindow)
		self.widget_tab_channelbox.setCurrentIndex(0)
		self.widget_tab_layers.setCurrentIndex(0)
		self.widget_tab_custom.setCurrentIndex(0)
		#QMetaObject.connectSlotsByName(MainWindow)
		
		self.button_settings.clicked.connect(self.settings_callback)
		
	def settings_callback(self):
		print True
	
	def retranslateUi(self, MainWindow):
		MainWindow.setWindowTitle(QApplication.translate("MainWindow", "MainWindow", None, -1))
		self.button_settings.setText(QApplication.translate("MainWindow", "...", None, -1))
		self.lineEdit.setText(QApplication.translate("MainWindow", "pSphere1", None, -1))
		self.treeWidget.headerItem().setText(0, QApplication.translate("MainWindow", "Attributes", None, -1))
		self.treeWidget.headerItem().setText(1, QApplication.translate("MainWindow", "Values", None, -1))
		__sortingEnabled = self.treeWidget.isSortingEnabled()
		self.treeWidget.setSortingEnabled(False)
		self.treeWidget.topLevelItem(0).setText(0, QApplication.translate("MainWindow", "Translate X", None, -1))
		self.treeWidget.topLevelItem(0).setText(1, QApplication.translate("MainWindow", "0", None, -1))
		self.treeWidget.topLevelItem(1).setText(0, QApplication.translate("MainWindow", "Translate Y", None, -1))
		self.treeWidget.topLevelItem(1).setText(1, QApplication.translate("MainWindow", "0", None, -1))
		self.treeWidget.topLevelItem(2).setText(0, QApplication.translate("MainWindow", "Translate Z", None, -1))
		self.treeWidget.topLevelItem(2).setText(1, QApplication.translate("MainWindow", "0", None, -1))
		self.treeWidget.topLevelItem(3).setText(0, QApplication.translate("MainWindow", "Rotate X", None, -1))
		self.treeWidget.topLevelItem(3).setText(1, QApplication.translate("MainWindow", "0", None, -1))
		self.treeWidget.topLevelItem(4).setText(0, QApplication.translate("MainWindow", "Rotate Y", None, -1))
		self.treeWidget.topLevelItem(4).setText(1, QApplication.translate("MainWindow", "0", None, -1))
		self.treeWidget.topLevelItem(5).setText(0, QApplication.translate("MainWindow", "Rotate Z", None, -1))
		self.treeWidget.topLevelItem(5).setText(1, QApplication.translate("MainWindow", "0", None, -1))
		self.treeWidget.topLevelItem(6).setText(0, QApplication.translate("MainWindow", "Scale X", None, -1))
		self.treeWidget.topLevelItem(6).setText(1, QApplication.translate("MainWindow", "0", None, -1))
		self.treeWidget.topLevelItem(7).setText(0, QApplication.translate("MainWindow", "Scale Y", None, -1))
		self.treeWidget.topLevelItem(7).setText(1, QApplication.translate("MainWindow", "0", None, -1))
		self.treeWidget.topLevelItem(8).setText(0, QApplication.translate("MainWindow", "Scale Z", None, -1))
		self.treeWidget.topLevelItem(8).setText(1, QApplication.translate("MainWindow", "0", None, -1))
		self.treeWidget.topLevelItem(9).setText(0, QApplication.translate("MainWindow", "Visibility", None, -1))
		self.treeWidget.topLevelItem(9).setText(1, QApplication.translate("MainWindow", "on", None, -1))
		self.treeWidget.setSortingEnabled(__sortingEnabled)
		self.widget_tab_channelbox.setTabText(self.widget_tab_channelbox.indexOf(self.tab_channelbox),
		                                      QApplication.translate("MainWindow", "Channel Box", None, -1))
		self.toolButton_3.setText(QApplication.translate("MainWindow", "...", None, -1))
		self.toolButton_2.setText(QApplication.translate("MainWindow", "...", None, -1))
		self.toolButton_4.setText(QApplication.translate("MainWindow", "...", None, -1))
		self.widget_tab_layers.setTabText(self.widget_tab_layers.indexOf(self.tab_layers),
		                                  QApplication.translate("MainWindow", "Layers", None, -1))
		self.widget_tab_layers.setTabText(self.widget_tab_layers.indexOf(self.tab_anim),
		                                  QApplication.translate("MainWindow", "Anim", None, -1))
		self.pushButton.setText(QApplication.translate("MainWindow", "PushButton", None, -1))
		self.widget_tab_custom.setTabText(self.widget_tab_custom.indexOf(self.tab_tools),
		                                  QApplication.translate("MainWindow", "Tools", None, -1))


if __name__ == "__main__":
	import sys
	
	app = QApplication(sys.argv)
	MainWindow = QMainWindow()
	ui = Ui_MainWindow()
	ui.setupUi(MainWindow)
	MainWindow.show()
	sys.exit(app.exec_())
